# ==========================================================
# asiste
# Configuration file
# ==========================================================

default:

  app:
    name: "asiste"
    version: "0.1.0"

  language: "es"

  timezone: "America/Argentina/Cordoba"

  google:

    # ID del Google Sheets (no la URL completa)
    sheet_id: "1tzLeVkurlV0_-FFY_bQA32G_xmIfTWIxR8oatLD2S9Y"

    # Hojas esperadas
    sheets:

      docentes: "Docentes"

      estudiantes: "Estudiantes"

      clases: "Clases"

      preguntas: "Preguntas"

      asistencia: "Asistencia"

      respuestas: "Respuestas"

  authentication:

    session_timeout: 3600

  qr:

    default_duration_minutes: 10

  ui:

    title: "asiste"

    theme: "flatly"

    # Se cambió a SVG para placeholders
    logo: "www/img/logo.svg"

    favicon: "www/favicon.svg"

development:

  verbose: TRUE

  cache: FALSE

production:

  verbose: FALSE

  cache: TRUE
